### ISSUE TITLE
In system_definition: ds not defined

### ISSUE THREAD

**Issue by finmod** [JuliaDynamics/DynamicalSystems.jl#44]
In system_definiion.jl, running:

@inline @inbounds function eom_roessler!(du, u)
    a = 0.2; b = 0.2; c = 5.7
    du[1] = -u[2]-u[3]
    du[2] = u[1] + a*u[2]
    du[3] = b + u[3]*(u[1] - c)
end
@inline @inbounds function jacob_roessler(u)
    i = one(eltype(u))
    o = zero(eltype(u))
    @SMatrix [o     -i      -i;
              i      a       o;
              u[3]   o       u[1] - c]
end

ros = ContinuousDS(rand(3), eom_roessler!, jacob_roessler)

produces this error:

UndefVarError: ds not defined

Stacktrace:
 [1] show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\DynamicalSystems\src\systems\continuous.jl:139
 [2] limitstringmime(::MIME{Symbol("text/plain")}, ::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\IJulia\src\inline.jl:24
 [3] display_dict(::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\IJulia\src\execute_request.jl:27
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Denis\.julia\v0.6\IJulia\src\execute_request.jl:182
 [5] eventloop(::ZMQ.Socket) at C:\Users\Denis\.julia\v0.6\IJulia\src\eventloop.jl:8
 [6] (::IJulia.##14#17)() at .\task.jl:335

**Comment by Datseris** [comment]
fixed on master, thanks!

**Comment by finmod** [comment]
Almost there. I still get this error for the same input as above:

UndefVarError: s not defined

Stacktrace:
 [1] show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\DynamicalSystems\src\systems\continuous.jl:140
 [2] limitstringmime(::MIME{Symbol("text/plain")}, ::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\IJulia\src\inline.jl:24
 [3] display_dict(::DynamicalSystems.ContinuousDS{Array{Float64,1},#eom_roessler!,#jacob_roessler}) at C:\Users\Denis\.julia\v0.6\IJulia\src\execute_request.jl:27
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Denis\.julia\v0.6\IJulia\src\execute_request.jl:182
 [5] eventloop(::ZMQ.Socket) at C:\Users\Denis\.julia\v0.6\IJulia\src\eventloop.jl:8
 [6] (::IJulia.##14#17)() at .\task.jl:335

**Comment by Datseris** [comment]
Damn coding is hard :P I now know why this happened: I only use juno!
